### ISSUE TITLE
Running moma fails throwing recursion depth exceded exception

### ISSUE THREAD

**Issue by azimov** [biosustain/cameo#101]
Executing lmoma with larger models causes recursion depth be exceed. This occurs on a model we are building but can be replicated on included BIGG models.
Occurs on Ubuntu 14.04, 16.04, 16.10. Manjaro 16.10 with Cameo version 0.8.0 and python versions 2.7 and 3.5

Code to replicate:

``import cameo``
``from cameo.flux_analysis import fba, lmoma``
``model = cameo.models.bigg.iJN746``
``ref = fba(model)``
``result = lmoma(model, reference=ref)``

Increasing maximum recursion depth with ``sys.setrecursionlimit(2000)`` also breaks, with python throwing a type error.

**Comment by phantomas1234** [comment]
I can reproduce the issue. @Midnighter can you take a look at this? The issue does not occur with the small ecoli model (`cameo.models.bigg.e_coli_core`).

**Comment by phantomas1234** [comment]
Fixed in https://github.com/biosustain/optlang/pull/59. Thanks for the feedback @azimov! If you upgrade optlang to 1.0.2 (`pip install optlang --upgrade`) the recursion issue should be gone. Please let us know otherwise. Alternatively you could also upgrade cameo to its current beta release 0.9.0b1 (`pip install cameo --pre`).
