### ISSUE TITLE
Cobrapy and Cameo FVA running time difference

### ISSUE THREAD

**Issue by MuhammedHasan** [biosustain/cameo#117]
Ubuntu 16.04
Python 3.5.2
solver: cplex

As I mention in this issue #114 cameo FVA runs slower although documentation claim [reverse](http://cameo.bio/04-analyze-models.html). Moreover, I observe same performance issue in multiple datasets. Especially, it causes a headache in the bigger dataset like recon2.

Thanks for your great interest.

**Comment by phantomas1234** [comment]
I am sorry, the documentation is a little out of date. When it was written, FVA on cobrapy would still take on the order of minutes to complete on the E. coli model iJO1366. I opened a pull request with a change that will bring cameo up to speed with the current cobrapy implementation. I hope I'll also find the time to make a new release. Are you in any case related to https://github.com/biosustain/cameo/issues/116? Because this is not about speed differences between cobrapy and cameo but a whole other issue.

If you're dealing with very large models you could benefit from parallelization of FVA on cameo (which you can't with cobrapy) if you have multiple CPU cores.

	from cameo.parallel import MultiprocessingView
	from cameo import models
	from cameo import flux_variability_analysis
	model = models.bigg.iJO1366.copy()
	flux_variability_analysis(model, view=MultiprocessingView())

Furthermore, if you're only interested in a few reactions you could run FVA for just those:

       flux_variability_analysis(model, reactions=[...])

**Comment by MuhammedHasan** [comment]
Thank for the pull request. I know, my issue is not related to issue you mentioned above.
